./adtTest.dlist <do1&> mydo1
./ref/adtTest-mac.dlist <do1&> refdo1
vimdiff mydo1 refdo1
./adtTest.dlist <do2&> mydo2
./ref/adtTest-mac.dlist <do2&> refdo2
vimdiff mydo2 refdo2
./adtTest.dlist <do3&> mydo3
./ref/adtTest-mac.dlist <do3&> refdo3
vimdiff mydo3 refdo3
./adtTest.dlist <do4&> mydo4
./ref/adtTest-mac.dlist <do4&> refdo4
vimdiff mydo4 refdo4
./adtTest.dlist <do5&> mydo5
./ref/adtTest-mac.dlist <do5&> refdo5
vimdiff mydo5 refdo5
